### PR TITLE
Campaigns Management

### PR DESCRIPTION
**Pull request by atzorvas**
Implements #121 
- [x] Functionality
- [x] Basic view templates
- [x] Specs
- [x] Push changes for abillity.rb in separate PR
- [x] Push change in application.html.erb in separate PR

This PR once ready should only change things related to Campaigns and not introduce changes elsewhere.

### CODE REVIEW

**Comment by atzorvas** [comment]
@craig-riecke I was about to branch-out for changes in `abillity.rb` and `application.html.erb` but I'm not sure if that will be bureaucracy only or not.

To all: anything to suggest/comment?

**Comment by craig-riecke** [comment]
@atzorvas If other people are depending on the changes to those two file, go ahead and pull them out.  They look good to me.

**Comment by atzorvas** [comment]
extracted to #139, I'll clear this commit PR in order to finalize it asap. WIP

**Comment by atzorvas** [comment]
I've cherry-picked #139 in order for this to be ready & passing without having conflicting code.

**Comment by atzorvas** [comment]
rebased with origin/master and conflict solved

**Comment by craig-riecke** [comment]
@atzorvas Is this ready for a code review and merge?

**Comment by atzorvas** [comment]
it has a bug with deleting a campaign, but solving #131 #127 and deciding what we want to do with the dependent recipient_families/recipients/organization_campaigns record will solve this. 

I'll open a new issue for the campaign destroy action, after the merge.

@craig-riecke feel free to review & merge if everything is good

**Comment by craig-riecke** [comment]
👍 Merging...

**Pull request merged**
