### PR TITLE
Org Admin Send Emails

### LINKED ISSUE #90: Organization: Send Emails
_Route_: GET /organization_campaign/_orgCampId_/send_email_form

A form with a rich text box (TinyMCE, since that's in our Gems), and a warning message about sending this email to 500 (or how many people are in the member list) members.  POST's to /organization_campaign/_orgCampId_/send_email which sends the actual email from the organization admin's email address.  The URL in the email will look like /organization_campaign/_orgCampId_ which we have built already in our RFG app.

### PR DESCRIPTION
**Pull request by craig-riecke**
Implements and fixes #90.   Note I shut off mailing in DEV altogether since Gmail now requires you to jump through hoops to use it as an SMTP mailer.  Automated tests mostly capture that mailing will do the right thing in prod.

### CODE REVIEW

**Comment by atzorvas** [comment]
I would prefer using a separate controller with views in order to handle the mailing stuff.

**Comment by craig-riecke** [comment]
Makes sense, but I'm not sure where to put it right now.  Constructing the email needs an Org and a Campaign, since that's how it builds the sample subject and body.  Sending an email needs to know the Org to get the members list for sending, at the very least.  If you called the resource POST /email or something, then emails would need an :id.

**Comment by atzorvas** [comment]
I was thinking of a notifications_controller, available as @/mail@.

While creating a notification, we could give the type of the mail we want to create, which would result into creating an object with the same class name. This class could have all the required and optional elements for constructing the notification as attributes, and composing it would be easy.

We could store the composed notifications as records in the database and thus having an ID to request them later on (probably as a "view online" feature) but we could also ignore storing them, at least for now.

That way we could simplify our controllers from having "send email" methods and we could have a clear way on what's required and what's optional while using controllers & views taking advantage of convention over configuration.

We could also skip this for now, and leave it as a future idea, and I'll probably create a PR at some time :smiley:

**Comment by craig-riecke** [comment]
@atzorvas Yeah, that was just the idea I needed.  Thanks!  Refactored into /mail/appeals, built a model for it (non-persisting for now), and restructured tests. Much nicer.  

Can someone take a look before I merge?

**Pull request merged**
