### PR TITLE
Edit Membership

### PR DESCRIPTION
**Pull request by craig-riecke**
Implements #88.

### CODE REVIEW

**Comment by craig-riecke** [comment]
Note, there is one Rubocop offense that I don't understand well enough to fix:

```
-> rubocop
Inspecting 100 files
.................C..................................................................................

Offenses:

app/controllers/memberships_controller.rb:34:3: C: Assignment Branch Condition size for update is too high. [24.17/15]
  def update
  ^^^

100 files inspected, 1 offense detected
```

**Comment by jaydorsey** [comment]
There's a few ways you can fix it:
- Disable rubocop for that method. 

```
# rubocop:disable Metrics/AbcSize
def update

end
# rubocop:enable Metrics/AbcSize
```
- Change the default rubocop setting to allow a greater rating/size for assignment branch conditions
- Refactor

I'd refactor if possible. Disable for that method if it's not possible. I wouldn't increase the size for the entire project unless you had a justification for it (other than "it keeps warning me" 😆 )

Could the check you have in the update method of the controller could be refactored so it's handled by the database validations & ActiveRecord validations?

**Comment by craig-riecke** [comment]
Ah yes ... as it turns out the duplicate email condition was already a validation that Devise added, so I just had to detect it!  Fixed now.

**Comment by craig-riecke** [comment]
I got impatient and tests passed, so I merged this in.

**Pull request merged**
